# -*- coding: utf-8 -*-
"""hw3_quick sort

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1efYklsI_xVlH02ia_55erlqoY30KYsvC
"""

def quick_sort(arr, depth=0):
    indent = "  " * depth
    if len(arr) <= 1:
        return arr

    pivot = arr[0]
    left = []
    right = []

    for i in range(1, len(arr)):
        if arr[i] < pivot:
            left.append(arr[i])
        else:
            right.append(arr[i])


    print(f"{indent}目前陣列：{arr}")
    print(f"{indent}選擇的 pivot：{pivot}")
    print(f"{indent}左邊（小於 pivot）：{left}")
    print(f"{indent}右邊（大於等於 pivot）：{right}")
    print()


    sorted_left = quick_sort(left, depth + 1)
    sorted_right = quick_sort(right, depth + 1)


    merged = sorted_left + [pivot] + sorted_right
    print(f"{indent}合併：{merged}\n")
    return merged


data = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]
print("🔢 【快速排序開始】\n")
sorted_result = quick_sort(data)
print("✅ 【最終排序結果】：", sorted_result)